[package]
name = "contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = "0.9.0"
casper-contract = "1.4.4"
casper-types = "1.5.0"

[features]
default = ["casper"]
casper = ["odra/casper"]
mock-vm = ["odra/mock-vm"]
